### ISSUE TITLE
GDPR friendly tools

### ISSUE THREAD

**Issue by pwab** [HankiDesign/COVID-19-Remote-Work-and-Study-Resources#2]
I'm not sure how this is handled in other countries but here in Germany we have to comply to GDPR and every cloud service that handles the data of coworkers (e.g. collaboration software, online office, messaging, etc.) or students (e.g. online courses, quiz and classroom software, etc.) is a Processor and must be treated like that (see Art. 28 GDPR). Therefore, you need to investigate their privacy standards and you need a contract based on Art. 28(3) GDPR.

The list is a good start for someone interested into remote work or remote teaching but would it be possible to highlight GDPR friendly tools or services? I'm talking about services which are hosted in the EU and comply to the GDPR or projects which offer the source code so you can implement an instance on your own server infrastructure.

**Comment by TimoSalomaki** [comment]
That's a very good point Philipp, thanks for the detailed explanation and reasoning behind your suggestion. I have an idea how to restructure the tables a bit to allow for information about GDPR compliancy and possible licensing/deployment types as well. Some organizations might only be interested in open source tools/services that they can deploy and modify as they wish while others might only want cloud hosted services that can be set up quickly when the need arises.

**Comment by TimoSalomaki** [comment]
I've now added the GDPR column. One could of course argue that some other information such as CCPA should be added but let's see if there's a need for it. GDPR is a great start and affects companies globally, even though it's only EU specific.
